stations = [("captain", "commander"),
            ("captain", "diplomat"),
            ("captain", "playboy"),
            ("engineering", "engineer"),
            ("engineering", "commander"),
            ("helm", "pilot"),
            ("helm", "engineer"),
            ("weapons", "engineer"),
            ("weapons", "warrior"),
            ("advisor", "diplomat"),
            ("advisor", "playboy")]

candidates = [("Linnea", "commander", 70),
              ("Linnea", "playboy", 80),
              ("Linnea", "pilot", 70),
              ("Linnea", "warrior", 50),
              ("Simon", "diplomat", 70),
              ("Simon", "pilot", 20),
              ("Mia", "engineer", 80),
              ("Mia", "pilot", 80),
              ("Mia", "commander", 50),
              ("Magnus", "engineer", 90),
              ("Magnus", "playboy", 20),
              ("Klara", "warrior", 80),
              ("Klara", "commander", 60)]